services:
  authgate:
    build: .
    environment:
      - PORT=3101
    expose:
      - "3000"
    ports:
      - "3000:3101"  
    networks:
      - gis_net

networks:
  gis_net:
    external: true
